# Use the official PostgreSQL image from the Docker Hub
FROM postgres:latest

# Set environment variables for the PostgreSQL database
ENV POSTGRES_USER=development
ENV POSTGRES_PASSWORD=development
ENV POSTGRES_DB=recipes

# Expose the PostgreSQL port
EXPOSE 5432

# Copy the initialization script to the Docker container
COPY init.sql /docker-entrypoint-initdb.d/

# The official PostgreSQL image automatically runs any scripts in /docker-entrypoint-initdb.d/